# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sample_pb2 as sample__pb2


class SampleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HelloServer = channel.stream_stream(
        '/sample.SampleService/HelloServer',
        request_serializer=sample__pb2.HelloMessage.SerializeToString,
        response_deserializer=sample__pb2.ReplyMessage.FromString,
        )


class SampleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HelloServer(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HelloServer': grpc.stream_stream_rpc_method_handler(
          servicer.HelloServer,
          request_deserializer=sample__pb2.HelloMessage.FromString,
          response_serializer=sample__pb2.ReplyMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sample.SampleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
